[conf]
# General configuration settings
# get_more_episode补全提供下载的所有剧集
get_more_episode = true
#sleep_time 检查间隔时间，单位秒
sleep_time = 3600


[RSS]
# RSS 订阅地址
url = https://mikanani.me/RSS/MyBangumi?token=

[download]
# 下载路径
download_path = /your/download/path
# 下载工具，当前支持qbittorrent
download_tool = qbittorrent

[qbittorrent]
# qbittorrent 地址,eg、127.0.0.1:9091
host = your.qbittorrent.host:port
# qbittorrent 用户名和密码
username = admin
password = adminadmin
download_tag = RSSAnimeTool


